export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/abhiramvishal/clawpilot",
	GITHUB_DISCUSSIONS: "https://github.com/abhiramvishal/clawpilot/discussions",
	DISCORD: "https://discord.gg/clawpilot",
	REDDIT: "https://reddit.com/r/ClawPilot",
	X: "https://x.com/clawpilot",
	LINKEDIN: "https://www.linkedin.com/company/clawpilot",
	TIKTOK: "https://www.tiktok.com/@roo.code",
	BLUESKY: "https://bsky.app/profile/clawpilot.bsky.social",
	YOUTUBE: "https://www.youtube.com/@ClawPilotYT",
	DOCUMENTATION: "https://docs.clawpilot.com",
	SLACK_DOCS: "https://docs.clawpilot.com/clawpilot-cloud/slack-integration",
	CAREERS: "https://careers.clawpilot.com",
	ISSUES: "https://github.com/abhiramvishal/clawpilot/issues",
	FEATURE_REQUESTS: "https://github.com/abhiramvishal/clawpilot/discussions/categories/feature-requests",
	COMMUNITY: "https://github.com/abhiramvishal/clawpilot/discussions",
	CHANGELOG: "https://github.com/abhiramvishal/clawpilot/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/abhiramvishal/clawpilot/blob/main/PRIVACY.md",
	INTEGRATIONS: "https://docs.clawpilot.com/community",
	TUTORIALS: "https://docs.clawpilot.com/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=clawpilot.clawpilot",
	SECURITY: "https://trust.clawpilot.com",
	EVALS: "https://clawpilot.com/evals",
	BLOG_SUBSTACK: "https://blog.clawpilot.com",
	OFFICE_HOURS_PODCAST: "https://www.youtube.com/@ClawPilotYT/podcasts",
	FAQ: "https://clawpilot.com/#faq",
	TESTIMONIALS: "https://clawpilot.com/#testimonials",
	CLOUD_APP_LOGIN: "https://app.clawpilot.com/sign-in",
	CLOUD_APP_SIGNUP: "https://app.clawpilot.com/sign-up",
	CLOUD_APP_SIGNUP_HOME: "https://app.clawpilot.com/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_SIGNUP_PRO: "https://app.clawpilot.com/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_TEAM_TRIAL: "https://app.clawpilot.com/checkout/team",
	SUPPORT: "mailto:support@clawpilot.com",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
	BLOG: "/blog",
}
