blank_issues_enabled: false
contact_links:
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=clawpilot.clawpilot&ssr=false#review-details
      about: Enjoying ClawPilot? Leave a review here!
